# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 868c0f5978295344373c29a923114f2dd78d23d542f1368d8d3147c30e70335ced364393efc5c567a5c3e0de0a7c1f153ad7e0440ceb57b3e35849b68fbb3177

test:
  secret_key_base: 07f6b5755fe5dce89c5a3977eb06a08ebce75480012cbcfb64ffc02ccf82a3f847e825660fb514ff1bae5d1831b4d8bcb1b3cc7d520307c0ad611551c5a39b6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
